In [1]:
import numpy as np
import pandas as pd

In [18]:
data = pd.read_csv('./data/store_chungbuk.csv', encoding='cp949')
df = pd.DataFrame(data)

# df.head()
df.keys()

/var/folders/t3/3hs6sjnx4152hbtrj0c_f_sw0000gn/T/ipykernel_75245/1125791892.py:1: DtypeWarning: Columns (0: 건물소유구분명) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./data/store_chungbuk.csv', encoding='cp949')

Index(['개방자치단체코드', '관리번호', '인허가일자', '영업상태명', '폐업일자', '소재지면적', '소재지우편번호',
       '도로명우편번호', '사업장명', '업태구분명', '데이터갱신구분', '건물소유구분명', '공장사무직직원수',
       '공장생산직직원수', '공장판매직직원수', '급수시설구분명', '남성종사자수', '다중이용업소여부', '데이터갱신시점',
       '도로명주소', '등급구분명', '보증액', '본사직원수', '상세영업상태명', '상세영업상태코드', '시설총규모',
       '여성종사자수', '영업상태코드', '영업장주변구분명', '월세액', '위생업태명', '전통업소주된음식', '전통업소지정번호',
       '전화번호', '좌표정보(X)', '좌표정보(Y)', '지번주소', '홈페이지', '최종수정시점'],
      dtype='str')

In [20]:
df.head()

,개방자치단체코드,관리번호,인허가일자,영업상태명,폐업일자,소재지면적,소재지우편번호,도로명우편번호,사업장명,업태구분명,...,월세액,위생업태명,전통업소주된음식,전통업소지정번호,전화번호,좌표정보(X),좌표정보(Y),지번주소,홈페이지,최종수정시점
0,4390000,4390000-104-2013-00053,2013-12-23,폐업,2021-12-22,10.50,380-966,27481.0,신세계분식,패스트푸드,...,NaN,패스트푸드,NaN,NaN,NaN,283572.331583,384363.647397,충청북도 충주시 호암동 157-1,NaN,2021-12-22 17:39:11
1,4390000,4390000-104-2024-00029,2024-04-24,폐업,2025-06-02,219.24,380-921,27447.0,카페반내,커피숍,...,NaN,커피숍,NaN,NaN,NaN,NaN,NaN,충청북도 충주시 중앙탑면 탑평리 493-24,NaN,2025-06-02 10:50:18
2,4390000,4390000-104-2024-00143,2024-12-12,폐업,2025-01-22,3.30,380-020,27387.0,지에스(GS)25성서점,편의점,...,NaN,편의점,NaN,NaN,NaN,NaN,NaN,충청북도 충주시 성서동 394,NaN,2025-01-22 13:53:13
3,4390000,4390000-104-2025-00039,2025-04-14,영업/정상,NaN,10.40,380-090,27398.0,미미,기타 휴게음식점,...,NaN,기타 휴게음식점,NaN,NaN,NaN,NaN,NaN,충청북도 충주시 용산동 1570,NaN,2025-04-14 17:05:22
4,4390000,4390000-104-2025-00140,2025-11-11,영업/정상,NaN,42.78,380-962,27342.0,듀,커피숍,...,NaN,커피숍,NaN,NaN,NaN,283258.847171,388081.726682,충청북도 충주시 연수동 621-6,NaN,2025-11-11 16:11:25

In [23]:
# df[(df['상호명'].strat_wi '케이에프씨') | (df['상호명'] == 'KFC')]

df[(df['사업장명'].str.startswith('케이에프씨') | df['사업장명'].str.startswith('KFC')) & (df['영업상태명'] != '폐업')]

,개방자치단체코드,관리번호,인허가일자,영업상태명,폐업일자,소재지면적,소재지우편번호,도로명우편번호,사업장명,업태구분명,...,월세액,위생업태명,전통업소주된음식,전통업소지정번호,전화번호,좌표정보(X),좌표정보(Y),지번주소,홈페이지,최종수정시점
17777,5710000,5730000-104-2013-02056,2013-07-29,영업/정상,NaN,189.01,361-801,28396.0,KFC(케이에프씨)청주메가폴리스점,패스트푸드,...,NaN,패스트푸드,NaN,NaN,432330669.0,238567.758444,347375.787333,충청북도 청주시 흥덕구 가경동 1416-2 대우메가폴리스 1A-001 일부(1층),NaN,2023-05-26 15:15:45

In [27]:
df[df['사업장명'].str.contains('케이에프씨')]

,개방자치단체코드,관리번호,인허가일자,영업상태명,폐업일자,소재지면적,소재지우편번호,도로명우편번호,사업장명,업태구분명,...,월세액,위생업태명,전통업소주된음식,전통업소지정번호,전화번호,좌표정보(X),좌표정보(Y),지번주소,홈페이지,최종수정시점
12298,5710000,5720000-104-1997-01012,1997-04-04,폐업,2002-03-08,253.71,360-011,NaN,케이에프씨청주매장,패스트푸드,...,NaN,패스트푸드,NaN,NaN,432568515.0,243650.511973,348405.604828,충청북도 청주시 상당구 북문로1가 162-7,NaN,2001-08-17 00:00:00
13382,5710000,5735000-104-2014-04046,2014-09-22,폐업,2017-03-28,258.18,363-883,28119.0,KFC(케이에프씨)청주오창매장,패스트푸드,...,NaN,패스트푸드,NaN,NaN,432149515.0,238354.473870,357049.632945,충청북도 청주시 청원구 오창읍 양청리 793-5 1층,NaN,2017-03-28 17:18:32
16394,5710000,5720000-104-2002-01064,2002-06-29,폐업,2017-09-20,185.55,360-011,28527.0,케이에프씨쥬네쓰매장,패스트푸드,...,NaN,패스트푸드,NaN,NaN,NaN,243582.088026,348339.218504,"충청북도 청주시 상당구 북문로1가 170-1 (1,2층)",NaN,2017-09-20 10:09:56
17777,5710000,5730000-104-2013-02056,2013-07-29,영업/정상,NaN,189.01,361-801,28396.0,KFC(케이에프씨)청주메가폴리스점,패스트푸드,...,NaN,패스트푸드,NaN,NaN,432330669.0,238567.758444,347375.787333,충청북도 청주시 흥덕구 가경동 1416-2 대우메가폴리스 1A-001 일부(1층),NaN,2023-05-26 15:15:45